tap "dart-lang/dart"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "luckyframework/lucky"
tap "sass/sass"
brew "ack"
brew "bandwhich"
brew "bat"
brew "bitwarden-cli"
brew "caddy"
brew "sqlite"
brew "composer"
brew "coreutils"
brew "defaultbrowser"
brew "diff-so-fancy"
brew "dnsmasq", restart_service: true
brew "docker", link: false
brew "ffmpeg"
brew "fzf"
brew "fzy"
brew "git"
brew "graphicsmagick"
brew "libyaml"
brew "mackup"
brew "mas"
brew "mysql", restart_service: true
brew "neovim"
brew "nginx", restart_service: true
brew "tmux"
brew "overmind"
brew "php", restart_service: true
brew "postgresql"
brew "pwgen"
brew "python"
brew "rbenv"
brew "rust"
brew "telnet"
brew "tldr"
brew "tree"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zplug"
brew "heroku/brew/heroku"
brew "sass/sass/sass"
cask "alfred"
cask "appcleaner"
cask "arq"
cask "authy"
cask "bartender"
cask "bettertouchtool"
cask "bitwarden"
cask "box-drive"
cask "colorsnapper"
cask "cyberduck"
cask "daisydisk"
cask "docker"
cask "dropbox"
cask "fantastical"
cask "figma"
cask "firefox"
cask "firefox-developer-edition"
cask "font-hack"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "forklift"
cask "google-chrome"
cask "google-chrome-canary"
cask "iina"
cask "imageoptim"
cask "iridium"
cask "istat-menus"
cask "iterm2"
cask "knockknock"
cask "logitech-gaming-software"
cask "microsoft-edge-canary"
cask "microsoft-remote-desktop-beta"
cask "microsoft-teams"
cask "mysqlworkbench"
cask "oversight"
cask "pennywise"
cask "pocket-casts"
cask "radio-silence"
cask "rectangle"
cask "slack"
cask "spotify"
cask "steermouse"
cask "sublime-text-dev"
cask "superduper"
cask "suspicious-package"
cask "sync"
cask "telegram-desktop"
cask "the-unarchiver"
cask "tunnelblick"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "waterfox"
cask "webpquicklook"
cask "xnconvert"
mas "Airmail", id: 918858936
mas "Dato", id: 1470584107
mas "Microsoft To Do", id: 1274495053
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Tweetbot", id: 1384080005
mas "Up Next", id: 1355117041
mas "Xcode", id: 497799835
