theme = "snazzy"

[editor]
line-number = "relative"
mouse = true
true-color = true
cursorline = true
auto-save = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
